require("plugins")
require("keymapping")
require("nvimtree")
require("config.terminal")
require("config.comments")
require("config.harpoon")
require("config.nvim_cmp")
require("config.auto_cmp")
require("config.git_signs")
require("colorscheme")
require("colorizer")
-- require("config.lualine")
require("config.tree-sitter")
require("options")
